apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: devorbitus/eso-updater
  newName: devorbitus/eso-updater
  newTag: 1.2.0

secretGenerator:
- envs:
  - configs/.env
  name: externalsecret-updater-user-secret

resources:
- manifests/service-account.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/cluster-role.yaml
- manifests/cluster-role-binding.yaml
- manifests/ingress.yaml
