apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsecret-updater-cluster-role
rules:
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
