apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: externalsecret-updater-cluster-binding
subjects:
  - kind: ServiceAccount
    name: externalsecret-updater-sa
    namespace: cgruel-sra
roleRef:
  kind: ClusterRole
  name: externalsecret-updater-cluster-role
  apiGroup: rbac.authorization.k8s.io
