apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: externalsecret-updater-role
rules:
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets"]
    verbs: ["get", "list", "update"]
