apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: externalsecret-updater-binding
subjects:
  - kind: ServiceAccount
    name: externalsecret-updater-sa
    namespace: cgruel-sra
roleRef:
  kind: Role
  name: externalsecret-updater-role
  apiGroup: rbac.authorization.k8s.io
