apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akeyless-external-secret-example
spec:
  # Set to 0s to NOT refresh the secret automatically
  refreshInterval: 24h

  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store

  target:
    name: akeyless-secret-to-create
    creationPolicy: Owner

  data:
    - secretKey: mySecretKey
      remoteRef:
        key: /Chris Gruel/events/Test1
