apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: eso-secret-config
    envs:
      - .env

resources:
  - secret-store.yaml
  - external-secret.yaml

generatorOptions:
  disableNameSuffixHash: true
