apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: akeyless-secret-store
spec:
  provider:
    akeyless:
      # Maps to the Akeyless Gateway API URL (default port 8081)
      akeylessGWApiURL: "https://unigw.cg.cs.akeyless.fans/api/v2"
      authSecretRef:
        kubernetesAuth:
          accessID: p-snbqrtx1o085km
          k8sConfName: "/Sandbox/Chris Gruel/sandbox sra cg"
          serviceAccountRef:
            name: cgruel-sra-sbx-sa
